### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.mixture.gmm'

### ISSUE THREAD

**Issue by Pittu7** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#1]
When trying to run the Voice Authentication part, then facing the following error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-df29f49ded81> in <module>
    158 
    159 if __name__ == '__main__':
--> 160     recognize()

<ipython-input-13-df29f49ded81> in recognize()
     42                 os.listdir(modelpath) if fname.endswith('.gmm')]
     43 
---> 44     models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
     45 
     46     speakers   = [fname.split("/")[-1].split(".gmm")[0] for fname 

<ipython-input-13-df29f49ded81> in <listcomp>(.0)
     42                 os.listdir(modelpath) if fname.endswith('.gmm')]
     43 
---> 44     models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
     45 
     46     speakers   = [fname.split("/")[-1].split(".gmm")[0] for fname

Please let me know on how to fix this.
Thank You.

**Comment by MohamadMerchant** [comment]
please check the version of scikit-learn is same as given in requirement.txt.

**Comment by Pittu7** [comment]
Thank you!
