### ISSUE TITLE
Voice Authentication

### ISSUE THREAD

**Issue by NiharThakkar** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#10]
In the Voice authentication part it is not detecting unknown voices and most of the time it recognises as the wrong user (Means if two users user1 and user2 are registered than it recognises user1 as user2). It is not working properly. Please Guide.

**Comment by MohamadMerchant** [comment]
For multiple users you need to record samples in a clear background for better predictions.

**Comment by NiharThakkar** [comment]
Okay, scores array, when the test.wav is compared to unknown.gmm than there are multiple values in scores array and it all adds up to - 20000 but when test.wav is compared to other gmm files than the scores array has only one value.
 for every sample that I record the log_likelihood value is -20000 for unknown.gmm and with other samples, it is -45, -40 etc. so that's y the answer is never 'unknown user', any reason for that ??

**Comment by NiharThakkar** [comment]
THE PROBLEM IS SOLVED  !! Thanks

**Comment by NiharThakkar** [comment]
But now New problem is that every user is recognised as an unknown user don't know y. I recorded the audio in a very quiet environment but still, every time the user is unknown.

**Comment by MohamadMerchant** [comment]
try running recognize_until_keyboard_interrupt.py for continuous recognition as for multiple users, if some times  the prediction probability is above the threshold than it must recognize after one or two times.
