### ISSUE TITLE
Concatenate all 3 sample features

### ISSUE THREAD

**Issue by XeonAngel** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#11]
To add a new user you said that you concatenate the features from all 3 voice samples.
To do this, aren't you suppose to declare FEATURE vectore before the actual FOR?
Like this:
![image](https://user-images.githubusercontent.com/37555201/81068603-50106f80-8ee9-11ea-948c-ba5f42002223.png)

**Comment by MohamadMerchant** [comment]
yes, I have changed it after but didn't pushed the changes. You can try it both the ways.
