### ISSUE TITLE
Face recognition failed

### ISSUE THREAD

**Issue by Vickey-ZWQ** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#12]
Hello Mohamad Merchant:  
  First of all, thank you very much for your contribution of Voice-Authentication-and-Face-Recognition project on Github. I've never seen project steps written in such detail so I really admire that! But I still have some problems and I sincerely hope I can get your help!

**Problem description：**
  I have successfully run add_user.py but when I run reconize_until_keyborad_interrupt.py, it show me  that voice can be recognized and face cant't ! It seems that some files are missing and I'm not sure which ones are missing. Here is a screenshot of the running process：
![Screenshot from 2020-05-18 18-45-17](https://user-images.githubusercontent.com/52652822/82206094-2c621600-993a-11ea-9b8f-41f068756487.png)

What I suppose to do?

**Comment by MohamadMerchant** [comment]
It seems your face is not registered properly. Please try adding your face again and in proper light with frontal face and try recognizing again, it should work. The other error is due to pyaudio dependency, you can try cleaning up your ALSA configuration files.
