### ISSUE TITLE
How to set unknown user in this project??

### ISSUE THREAD

**Issue by RushiKawade** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#5]

**Comment by RushiKawade** [comment]
how i set profile of unknown user which will get predicted if unkown voice sample is given.

**Comment by MohamadMerchant** [comment]
You don't have to set profile for unknown users, For voice authentication the sample unknown.gmm is provided in gmm models directory, that will be used for unknown voices and in face recognition, if the confidence threshold is below the limit than unknown face msg will be shown.

**Comment by RushiKawade** [comment]
Thanks
