### ISSUE TITLE
How to create unknow.gmm for my own data??

### ISSUE THREAD

**Issue by RushiKawade** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#6]
I tried with your unknown.gmm file but is not predicting unregistred user as unknown user. please help me.

**Comment by MohamadMerchant** [comment]
unknown.gmm is created by mixing lots of random sound samples and compressing all of them as one to make sure any other data than registered users will be recognized as unknown.
As it is not predicting unknown, You can remove all users data and try adding new users with clear background and clear voice samples. It will surely work.

**Comment by RushiKawade** [comment]
Does that random sample contain user voice sample or complete different
sounds files.

**Comment by MohamadMerchant** [comment]
It contains different random samples from different users.

**Comment by RushiKawade** [comment]
Where do you got such files. Pls suggest dataset. Thanks for your quick
responses.

**Comment by MohamadMerchant** [comment]
http://www.openslr.org/12/

**Comment by RushiKawade** [comment]
Compress means to make 1 gmm file  of all random sample

**Comment by MohamadMerchant** [comment]
yes, mixed and concated some part of samples.
