### ISSUE TITLE
calculate_delta

### ISSUE THREAD

**Issue by DivyaAgarwal17** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#7]
Hi , 
Can you please let me know what does calculate_delta function does post preprocessing.scale function in main_functions.py?.

**Comment by MohamadMerchant** [comment]
calculate delta function measures the changes in features from the previous frame to the next frame. delta feature extracted as the first derivative of MFCC feature represents the change between frames. You can read more about MFCC features to gain more detailed information.
