### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by cyonghui81** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#9]
Can i ask what is the exact environment you ran the models. E.g. python version and so on, they are not specified in your requirements.txt

Thanks alot.

Anyway i can retrain the models using my own data ?

**Comment by MohamadMerchant** [comment]
I have updated requirements.txt and you can use python3.6.9 or greater.
Yes you can perform transfer learning on the pretrained models.
